import java.awt.Graphics;

/**
 *
 * @author Viruz
 */
public class Ventana extends javax.swing.JFrame {
private final Rectangulo miRectangulo;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        miRectangulo = new Rectangulo();
        
        setExtendedState(6);
    }
    
    @Override
     public void paint(Graphics g){
        miRectangulo.dibujar(g);
    }
    
    public void dibujar() {
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Viruz Blog: Rectangulo con Scanner");
        setBackground(new java.awt.Color(255, 255, 255));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
